POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "1212",
    "dateOfBirth": "20045-5",
    "gender": "female",
    "occupation": "piano",
    "ssn": "22222"
}

###
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667


###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "date": "2015-01-02",
    "type": "OccupationalHealthcare",
    "specialist": "122",
    "description": "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
    "employerName": "hahaha",
    "sickLeave": {
      "startDate": "2015-01-02",
      "endDate": "2015-01-02"
    }
}