##get all##
GET http://localhost:3001/api/blogs

###delete blog###
DELETE http://localhost:3001/api/blogs/

###create blog###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpZCI6IjYxNTU0ODgxNmMxYzk0Y2JmYzM1MWZhMSIsImlhdCI6MTYzMjk3OTE0M30.CAOSs235OCSg0ax126neDxrK25GNI6rEiErpEl8c6gA

{
    "title": "7 habits",
    "author": "Stiven",
    "url": "77hhbb.org",
    "likes": 10
}