POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root2",
    "password": "somePassword123",
    "name": "Anthony"
}

######################
GET http://localhost:3001/api/users/


######################
DELETE http://localhost:3001/api/users/
