POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "newuser",
    "password": "newuser",
    "name": "Jackass"
}

######################
GET http://localhost:3001/api/users/


######################
DELETE http://localhost:3001/api/users/
